project_config:
  project_name: anomaly_detection
  experiment_name: baseline
  track_in_clearml: false
  seed: 13
  logs_dir: logs

data_config:
  class_path: anomalib.data.Folder
  init_args:
    name: skoly
    root: ./data/dead_pixels
    train_batch_size: 1
    eval_batch_size: 1
    num_workers: 8
    task: detection
    image_size: [512, 512]
    transform: null
    train_transform: null
    eval_transform: null
    test_split_mode: from_dir
    test_split_ratio: 0.2
    val_split_mode: same_as_test
    val_split_ratio: 0.5
    seed: null
    normal_dir: normal
    abnormal_dir: anomaly
    mask_dir: masks

# model:
#   class_path: anomalib.models.EfficientAd
#   init_args:
#     teacher_out_channels: 384
#     model_size: small
#     lr: 0.0001
#     weight_decay: 1.0e-05
model:
  class_path: anomalib.models.Patchcore
  init_args:
    backbone: wide_resnet50_2
    layers:
      - layer2
      - layer3
    pre_trained: true
    coreset_sampling_ratio: 0.1
    num_neighbors: 9


metrics:
  pixel:
    - AUPIMO

trainer_config:
  accelerator: gpu # <cpu, gpu, tpu, ipu, hpu, auto>
  benchmark: false
  check_val_every_n_epoch: 1 # Don't validate before extracting features.
  default_root_dir: logs
  detect_anomaly: false
  deterministic: false
  devices: 1
  enable_checkpointing: true
  enable_model_summary: true
  enable_progress_bar: true
  fast_dev_run: false
  gradient_clip_val: 0
  limit_predict_batches: 1.0
  limit_test_batches: 1.0
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  log_every_n_steps: 50
  max_epochs: 20
  max_steps: -1
  max_time: null
  min_epochs: 4
  min_steps: null
  num_nodes: 1
  num_sanity_val_steps: 0
  overfit_batches: 0.0
  plugins: null
  precision: 32
  profiler: null
  reload_dataloaders_every_n_epochs: 0
  strategy: auto
  sync_batchnorm: false
  val_check_interval: 1.0

# metrics:
#   image:
#     - F1Score
#     - AUROC
#   pixel:
#     - F1Score
#     - AUROC
#   threshold:
#     image_default: 0
#     pixel_default: 0
#     adaptive: true

# visualization:
#   show_images: False # show images on the screen
#   save_images: True # save images to the file system
#   log_images: True # log images to the available loggers (if any)
#   image_save_path: null # path to which images will be saved
#   mode: full # options: [full, simple]
